services:
    web:
        build: .
        container_name: talana-web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: codeigniter4
            MYSQL_USER: ci_user
            MYSQL_PASSWORD: ci_pass
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes: 
    db_data:
        